### PR TITLE
improvements and fixes

### PR DESCRIPTION
**Pull request by ChristopherTracey**
I moved this over to the ThinkBox, so paths may need to be updated.

### CODE REVIEW

**Comment by dyeany** [comment]
Does this mean the current script I have for testing won't work now?

**Comment by ChristopherTracey** [comment]
Yes, you could sync it and make some adjustments when it downloads. Nothing major and most everything should be easy to fix.

You should also get a copy of the sqlite db from my X drive.

**Comment by dyeany** [comment]
A new copy of squlite db? Molly and I set this up on Friday, but has the db changed then?

**Comment by ChristopherTracey** [comment]
The whole state and all the SGCN is in there now.

**Pull request merged**
